name: 'badger23-contribution-graph'
description: 'Generates a contribution graph that you can use on your github profile'
branding:
  icon: calendar
  color: orange
inputs:
  token:
    description: "Personal access token that meets the scope criteria for Github GraphQL API"
    required: true
  title:
    description: "Title to appear on graph"
    required: false
    default: "Contribution Graph"
  viewby:
    description: "day, week, month"
    required: true
    default: 'day'
  farback:
    description: "Amount of 'viewby' to go back on our graph. You cannot exceed a year as per github requirements"
    required: false
    default: 14
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jbraunsmajr/contributiongraph:master'
  args:
    - '-t'
    - ${{ inputs.token }}
    - '-v'
    - ${{ inputs.viewby }}
    - '-f'
    - ${{ inputs.farback }}
    - '-l'
    - ${{ inputs.title }}
